---
# - name: OSX | Install homebrew
#   command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- name: OSX | Tap homebrew cask
  homebrew_tap: tap=caskroom/cask state=present

- name: OSX | Install cask
  homebrew: name='brew-cask' state=latest update_homebrew=yes

- name: OSX | Install homebrew applications
  homebrew: name={{ item }} state=present
  with_items:
    - archey
    - hub

- name: OSX | Install homebrew cask applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
    - caffeine
    - flycut
    - flux
    - google-chrome
    - iterm2
    - seil
    - slack
    - ubersicht

- name: Add archey configuration
  copy: src=archey-logo dest=~/.config/ mode=0644

- name: Add archey dotfile
  copy: src=archey.dotfile dest=~/.dotfiles/ mode=0644
